[package]
name = "shoals"
version = "0.3.0"
compiler = "=0.6.0"
module_prefix = "Shoals"
additional_sources = ["properties", "references"]

[dependencies]
chelis-std = { version = "0.2.0" }
nautilus = { version = "0.6.0" }
coral = { version = "0.6.0" }
