module Shoals.Tests.CurvesBasis
import Std.Test (assert_close, assert_true)
import Shoals.Curves (YieldCurve, yield_curve_from_pillars, discount_factor, CurveBasis, curve_basis_from_pillars, basis_spread_at, discount_factor_with_basis)
def test_basis_zero_spread_equals_domestic_df() -> unit ! { Test } = {
  dom_times = to_tensor([cast(1.0, f32), cast(2.0, f32), cast(3.0, f32)])
  dom_rates = to_tensor([cast(0.03, f32), cast(0.04, f32), cast(0.045, f32)])
  dom = yield_curve_from_pillars(dom_times, dom_rates)
  b_times = to_tensor([cast(1.0, f32), cast(2.0, f32), cast(3.0, f32)])
  b_spreads = to_tensor([cast(0.0, f32), cast(0.0, f32), cast(0.0, f32)])
  basis = curve_basis_from_pillars(b_times, b_spreads)
  df_dom = discount_factor(dom, cast(1.5, f32))
  df_basis = discount_factor_with_basis(dom, basis, cast(1.5, f32))
  assert_close(df_basis, df_dom, cast(0.00001, f32), "zero spread => basis DF == domestic DF")
}
def test_basis_positive_spread_lowers_df() -> unit ! { Test } = {
  dom_times = to_tensor([cast(1.0, f32), cast(2.0, f32), cast(3.0, f32)])
  dom_rates = to_tensor([cast(0.03, f32), cast(0.04, f32), cast(0.045, f32)])
  dom = yield_curve_from_pillars(dom_times, dom_rates)
  b_times = to_tensor([cast(1.0, f32), cast(2.0, f32), cast(3.0, f32)])
  b_spreads = to_tensor([cast(0.005, f32), cast(0.005, f32), cast(0.005, f32)])
  basis = curve_basis_from_pillars(b_times, b_spreads)
  df_dom = discount_factor(dom, cast(2.0, f32))
  df_basis = discount_factor_with_basis(dom, basis, cast(2.0, f32))
  assert_true(lt(df_basis, df_dom), "positive spread => DF strictly less than domestic DF")
}
def test_basis_triangle_parity() -> unit ! { Test } = {
  ts = to_tensor([cast(1.0, f32), cast(2.0, f32), cast(3.0, f32)])
  usd_eur_s = to_tensor([cast(0.005, f32), cast(0.005, f32), cast(0.005, f32)])
  eur_jpy_s = to_tensor([cast(-0.003, f32), cast(-0.003, f32), cast(-0.003, f32)])
  jpy_usd_s = to_tensor([cast(-0.002, f32), cast(-0.002, f32), cast(-0.002, f32)])
  b_usd_eur = curve_basis_from_pillars(ts, usd_eur_s)
  b_eur_jpy = curve_basis_from_pillars(ts, eur_jpy_s)
  b_jpy_usd = curve_basis_from_pillars(ts, jpy_usd_s)
  t_query = cast(1.7, f32)
  s1 = basis_spread_at(b_usd_eur, t_query)
  s2 = basis_spread_at(b_eur_jpy, t_query)
  s3 = basis_spread_at(b_jpy_usd, t_query)
  total = add(s1, add(s2, s3))
  assert_close(total, cast(0.0, f32), cast(0.0001, f32), "triangle basis sum == 0 (no-arb)")
}
def test_basis_spread_at_interpolates() -> unit ! { Test } = {
  b_times = to_tensor([cast(1.0, f32), cast(2.0, f32), cast(3.0, f32)])
  b_spreads = to_tensor([cast(0.002, f32), cast(0.006, f32), cast(0.01, f32)])
  basis = curve_basis_from_pillars(b_times, b_spreads)
  s_mid = basis_spread_at(basis, cast(1.5, f32))
  _ = assert_close(s_mid, cast(0.004, f32), cast(0.00001, f32), "linear interp midpoint between 1y and 2y pillars")
  s_pillar = basis_spread_at(basis, cast(2.0, f32))
  _ = assert_close(s_pillar, cast(0.006, f32), cast(1e-7, f32), "pillar value exact at t=2")
  s_quarter = basis_spread_at(basis, cast(2.25, f32))
  assert_close(s_quarter, cast(0.007, f32), cast(0.00001, f32), "linear interp 25% between 2y and 3y pillars")
}
def test_discount_factor_with_basis_responds_to_domestic_curve() -> unit ! { Test } = {
  times = to_tensor([cast(1.0, f32), cast(2.0, f32), cast(3.0, f32)])
  low_rates = to_tensor([cast(0.03, f32), cast(0.04, f32), cast(0.045, f32)])
  high_rates = to_tensor([cast(0.08, f32), cast(0.09, f32), cast(0.095, f32)])
  dom_low = yield_curve_from_pillars(times, low_rates)
  dom_high = yield_curve_from_pillars(times, high_rates)
  b_spreads = to_tensor([cast(0.002, f32), cast(0.004, f32), cast(0.006, f32)])
  basis = curve_basis_from_pillars(times, b_spreads)
  df_low = discount_factor_with_basis(dom_low, basis, cast(1.5, f32))
  df_high = discount_factor_with_basis(dom_high, basis, cast(1.5, f32))
  assert_true(lt(df_high, df_low), "a higher domestic curve must lower the basis-adjusted DF")
}
