module Shoals.Tests.Tenor
import Std.Test (assert_eq_int, assert_true)
import Std.Time (date, days_between)
import Shoals.Tenor (Tenor, TenorUnit, tenor, tenor_to_days, tenor_apply, days_per_unit, overnight, tomorrow_next, spot_next, days_n, weeks_n, months_n, years_n, parse_tenor)
def test_days_per_unit_day() -> unit ! { Test } = assert_eq_int(days_per_unit(Day), cast(1, int64), "Day = 1")
def test_days_per_unit_week() -> unit ! { Test } = assert_eq_int(days_per_unit(Week), cast(7, int64), "Week = 7")
def test_days_per_unit_month_approx() -> unit ! { Test } = assert_eq_int(days_per_unit(Month), cast(30, int64), "Month ~ 30 (alpha)")
def test_days_per_unit_year_approx() -> unit ! { Test } = assert_eq_int(days_per_unit(Year), cast(365, int64), "Year ~ 365 (alpha)")
def test_days_per_unit_overnight() -> unit ! { Test } = assert_eq_int(days_per_unit(Overnight), cast(1, int64), "ON = 1")
def test_days_per_unit_tn() -> unit ! { Test } = assert_eq_int(days_per_unit(TomorrowNext), cast(2, int64), "TN = 2")
def test_days_per_unit_sn() -> unit ! { Test } = assert_eq_int(days_per_unit(SpotNext), cast(3, int64), "SN = 3")
def test_three_months_to_days() -> unit ! { Test } = assert_eq_int(tenor_to_days(months_n(cast(3, int64))), cast(90, int64), "3M ~ 90 days (alpha)")
def test_one_year_to_days() -> unit ! { Test } = assert_eq_int(tenor_to_days(years_n(cast(1, int64))), cast(365, int64), "1Y ~ 365 days (alpha)")
def test_thirty_years_to_days() -> unit ! { Test } = assert_eq_int(tenor_to_days(years_n(cast(30, int64))), cast(10950, int64), "30Y ~ 30*365 days (alpha)")
def test_tenor_apply_advances_date() -> unit ! { Test } = {
  ref = date(cast(2025, int64), cast(6, int64), cast(15, int64))
  shifted = tenor_apply(months_n(cast(3, int64)), ref)
  delta = days_between(ref, shifted)
  assert_eq_int(delta, cast(90, int64), "tenor_apply advances by 90 days for 3M (alpha)")
}
def test_overnight_constructor() -> unit ! { Test } = assert_eq_int(tenor_to_days(overnight()), cast(1, int64), "overnight() = 1 day")
def test_tn_constructor() -> unit ! { Test } = assert_eq_int(tenor_to_days(tomorrow_next()), cast(2, int64), "tomorrow_next() = 2 days")
def test_sn_constructor() -> unit ! { Test } = assert_eq_int(tenor_to_days(spot_next()), cast(3, int64), "spot_next() = 3 days")
def test_negative_tenor() -> unit ! { Test } = assert_eq_int(tenor_to_days(days_n(cast(-5, int64))), cast(-5, int64), "negative tenor for past dates")
def test_parse_3m() -> unit ! { Test } = assert_eq_int(tenor_to_days(parse_tenor("3M")), cast(90, int64), "parse_tenor 3M -> 90 days")
def test_parse_1y() -> unit ! { Test } = assert_eq_int(tenor_to_days(parse_tenor("1Y")), cast(365, int64), "parse_tenor 1Y -> 365 days")
def test_parse_30y() -> unit ! { Test } = assert_eq_int(tenor_to_days(parse_tenor("30Y")), cast(10950, int64), "parse_tenor 30Y -> 30*365 days")
def test_parse_2w() -> unit ! { Test } = assert_eq_int(tenor_to_days(parse_tenor("2W")), cast(14, int64), "parse_tenor 2W -> 14 days")
def test_parse_7d() -> unit ! { Test } = assert_eq_int(tenor_to_days(parse_tenor("7D")), cast(7, int64), "parse_tenor 7D -> 7 days")
def test_parse_overnight() -> unit ! { Test } = assert_eq_int(tenor_to_days(parse_tenor("ON")), cast(1, int64), "parse_tenor ON -> 1 day")
def test_parse_tomorrow_next() -> unit ! { Test } = assert_eq_int(tenor_to_days(parse_tenor("TN")), cast(2, int64), "parse_tenor TN -> 2 days")
def test_parse_spot_next() -> unit ! { Test } = assert_eq_int(tenor_to_days(parse_tenor("SN")), cast(3, int64), "parse_tenor SN -> 3 days")
