module Shoals.Tests.Trees
import Std.Test (assert_true)
import Shoals.Pricing (bs_call_scalar)
import Shoals.Trees (tr_crr_european_call, tr_crr_european_put, tr_crr_american_call, tr_crr_american_put, tr_tian_european_call, tr_jr_european_call, tr_trinomial_european_call)
def tr_abs(x: f32) -> f32 = if lt(x, cast(0.0, f32)) then neg(x) else x
def test_crr_european_call_converges_to_bs() -> unit ! { Test } = {
  s0 = cast(100.0, f32)
  k = cast(100.0, f32)
  r = cast(0.05, f32)
  q = cast(0.0, f32)
  sigma = cast(0.2, f32)
  t = cast(1.0, f32)
  bs = bs_call_scalar(s0, k, r, sigma, t)
  p_50 = tr_crr_european_call(s0, k, r, q, sigma, t, cast(50, int64))
  p_200 = tr_crr_european_call(s0, k, r, q, sigma, t, cast(200, int64))
  p_800 = tr_crr_european_call(s0, k, r, q, sigma, t, cast(800, int64))
  e_50 = tr_abs(sub(p_50, bs))
  e_200 = tr_abs(sub(p_200, bs))
  e_800 = tr_abs(sub(p_800, bs))
  monotone_a = lt(e_200, e_50)
  monotone_b = lt(e_800, e_200)
  tight = lt(e_800, cast(0.02, f32))
  assert_true(and(monotone_a, and(monotone_b, tight)), "CRR European call ATM error monotone-decreases over n_steps in {50,200,800} and is <0.02 vs Black-Scholes at n_steps=800")
}
def test_jr_european_call_converges_to_bs() -> unit ! { Test } = {
  s0 = cast(100.0, f32)
  k = cast(100.0, f32)
  r = cast(0.05, f32)
  q = cast(0.0, f32)
  sigma = cast(0.2, f32)
  t = cast(1.0, f32)
  bs = bs_call_scalar(s0, k, r, sigma, t)
  p_800 = tr_jr_european_call(s0, k, r, q, sigma, t, cast(800, int64))
  err = tr_abs(sub(p_800, bs))
  assert_true(lt(err, cast(0.02, f32)), "Jarrow-Rudd European call ATM matches Black-Scholes to within 0.02 at n_steps=800")
}
def test_tian_european_call_converges_to_bs() -> unit ! { Test } = {
  s0 = cast(100.0, f32)
  k = cast(100.0, f32)
  r = cast(0.05, f32)
  q = cast(0.0, f32)
  sigma = cast(0.2, f32)
  t = cast(1.0, f32)
  bs = bs_call_scalar(s0, k, r, sigma, t)
  p_800 = tr_tian_european_call(s0, k, r, q, sigma, t, cast(800, int64))
  err = tr_abs(sub(p_800, bs))
  assert_true(lt(err, cast(0.02, f32)), "Tian moment-matching European call ATM matches Black-Scholes to within 0.02 at n_steps=800")
}
def test_trinomial_european_call_converges_to_bs() -> unit ! { Test } = {
  s0 = cast(100.0, f32)
  k = cast(100.0, f32)
  r = cast(0.05, f32)
  q = cast(0.0, f32)
  sigma = cast(0.2, f32)
  t = cast(1.0, f32)
  bs = bs_call_scalar(s0, k, r, sigma, t)
  p_100 = tr_trinomial_european_call(s0, k, r, q, sigma, t, cast(100, int64))
  p_200 = tr_trinomial_european_call(s0, k, r, q, sigma, t, cast(200, int64))
  p_400 = tr_trinomial_european_call(s0, k, r, q, sigma, t, cast(400, int64))
  e_100 = tr_abs(sub(p_100, bs))
  e_200 = tr_abs(sub(p_200, bs))
  e_400 = tr_abs(sub(p_400, bs))
  monotone_a = lt(e_200, e_100)
  monotone_b = lt(e_400, e_200)
  rate_ok = lt(e_400, mul(cast(0.6, f32), e_200))
  tight = lt(e_400, cast(0.005, f32))
  assert_true(and(monotone_a, and(monotone_b, and(rate_ok, tight))), "Boyle trinomial European call ATM error monotone-decreases over n_steps in {100,200,400}, halves at each doubling (O(1/n) rate), and is <0.005 vs Black-Scholes at n_steps=400")
}
def test_crr_american_put_ge_european() -> unit ! { Test } = {
  s0 = cast(100.0, f32)
  k = cast(110.0, f32)
  r = cast(0.05, f32)
  q = cast(0.0, f32)
  sigma = cast(0.3, f32)
  t = cast(1.0, f32)
  n_steps = cast(200, int64)
  p_eu = tr_crr_european_put(s0, k, r, q, sigma, t, n_steps)
  p_am = tr_crr_american_put(s0, k, r, q, sigma, t, n_steps)
  finite_eu = and(gt(p_eu, cast(0.0, f32)), lt(p_eu, k))
  finite_am = and(gt(p_am, cast(0.0, f32)), lt(p_am, k))
  am_ge_eu = gte(p_am, p_eu)
  assert_true(and(finite_eu, and(finite_am, am_ge_eu)), "CRR ITM American put (s0=100, K=110, r=5%, q=0, sigma=30%, T=1) is finite, positive, and prices at least the European put under the same tree")
}
def test_crr_american_call_no_div_equals_european() -> unit ! { Test } = {
  s0 = cast(100.0, f32)
  k = cast(100.0, f32)
  r = cast(0.05, f32)
  q = cast(0.0, f32)
  sigma = cast(0.2, f32)
  t = cast(1.0, f32)
  n_steps = cast(200, int64)
  p_eu = tr_crr_european_call(s0, k, r, q, sigma, t, n_steps)
  p_am = tr_crr_american_call(s0, k, r, q, sigma, t, n_steps)
  diff = tr_abs(sub(p_am, p_eu))
  assert_true(lt(diff, cast(0.001, f32)), "CRR American call with q=0 equals European call within 0.001 at n_steps=200 (early exercise never optimal on a non-dividend-paying underlying)")
}
def test_crr_put_call_parity_european() -> unit ! { Test } = {
  s0 = cast(100.0, f32)
  k = cast(100.0, f32)
  r = cast(0.05, f32)
  q = cast(0.0, f32)
  sigma = cast(0.2, f32)
  t = cast(1.0, f32)
  n_steps = cast(200, int64)
  p_call = tr_crr_european_call(s0, k, r, q, sigma, t, n_steps)
  p_put = tr_crr_european_put(s0, k, r, q, sigma, t, n_steps)
  lhs = sub(p_call, p_put)
  rhs = sub(s0, mul(k, exp(neg(mul(r, t)))))
  diff = tr_abs(sub(lhs, rhs))
  assert_true(lt(diff, cast(0.005, f32)), "European put-call parity holds on the CRR tree: P_call - P_put = S0 - K*exp(-r*T) within 0.005 at n_steps=200 (no-arbitrage tautology in a recombining binomial)")
}
